= Composite Pattern
---
:toc:
:toclevels: 3
---

== Intent
Compose objects into tree structures to represent part-whole
hierarchies. Composite lets clients treat individual objects and compositions
of objects uniformly.

== Explanation

Real world example

> Every sentence is composed of words which are in turn composed of characters. Each of these objects is printable and they can have something printed before or after them like sentence always ends with full stop and word always has space before it

In plain words

> Composite pattern lets clients treat the individual objects in a uniform manner.

Wikipedia says

> In software engineering, the composite pattern is a partitioning design pattern. The composite pattern describes that a group of objects is to be treated in the same way as a single instance of an object. The intent of a composite is to "compose" objects into tree structures to represent part-whole hierarchies. Implementing the composite pattern lets clients treat individual objects and compositions uniformly.

**Programmatic Example**

Taking our sentence example from above. Here we have the base class and different printable types

[source,kotlin]
.LetterComposite.kt
----
abstract class LetterComposite {

    private val children = arrayListOf<LetterComposite>()

    fun add(letter:LetterComposite) {
        children.add(letter)
    }

    val count:Int get() = children.size

    protected open fun onBeforePrint() {}
    protected open fun onAfterPrint() {}

    fun print() {
        onBeforePrint()

        children.forEach { it.print() }

        onAfterPrint()
    }
}

class Letter(private val c: Char): LetterComposite() {

    override fun onBeforePrint() {
        print(c)
    }
}

class Word(letters:Iterable<Letter>) : LetterComposite() {

    init {
        letters.forEach { add(it) }
    }

    override fun onBeforePrint() {
        print(" ")
    }
}

class Sentence(words: Iterable<Word>): LetterComposite() {
    init {
        words.forEach { add(it) }
    }

    override fun onAfterPrint() {
        print(".")
    }
}
----

Then we have a messenger to carry messages

[source,kotlin]
.Messenger.kt
----
class Messenger {

    fun messageFromOrcs(): LetterComposite {
        val words = arrayListOf<Word>()

        words.add(Word(listOf(Letter('W'), Letter('h'), Letter('e'), Letter('r'), Letter('e'))))
        words.add(Word(listOf(Letter('t'), Letter('h'), Letter('e'), Letter('r'), Letter('e'))))
        words.add(Word(listOf(Letter('i'), Letter('s'))))
        words.add(Word(listOf(Letter('a'))))
        words.add(Word(listOf(Letter('w'), Letter('h'), Letter('i'), Letter('p'))))
        words.add(Word(listOf(Letter('t'), Letter('h'), Letter('e'), Letter('r'), Letter('e'))))
        words.add(Word(listOf(Letter('i'), Letter('s'))))
        words.add(Word(listOf(Letter('a'))))
        words.add(Word(listOf(Letter('w'), Letter('a'), Letter('y'))))

        return Sentence(words)
    }

    fun messageFromElves(): LetterComposite {

        val words = arrayListOf<Word>()

        words.add(Word(listOf(Letter('M'), Letter('u'), Letter('c'), Letter('h'))))
        words.add(Word(listOf(Letter('w'), Letter('i'), Letter('n'), Letter('d'))))
        words.add(Word(listOf(Letter('p'), Letter('o'), Letter('u'), Letter('r'), Letter('s'))))
        words.add(Word(listOf(Letter('f'), Letter('r'), Letter('o'), Letter('m'))))
        words.add(Word(listOf(Letter('y'), Letter('o'), Letter('u'), Letter('r'))))
        words.add(Word(listOf(Letter('m'), Letter('o'), Letter('u'), Letter('t'), Letter('h'))))

        return Sentence(words)
    }
}
----

And then it can be used as

[source,java]
----
LetterComposite orcMessage = new Messenger().messageFromOrcs();
orcMessage.print(); // Where there is a whip there is a way.
LetterComposite elfMessage = new Messenger().messageFromElves();
elfMessage.print(); // Much wind pours from your mouth.
----

## Applicability
Use the Composite pattern when

* you want to represent part-whole hierarchies of objects
* you want clients to be able to ignore the difference between compositions of objects and individual objects. Clients will treat all objects in the composite structure uniformly

## Real world examples

* http://docs.oracle.com/javase/8/docs/api/java/awt/Container.html[java.awt.Container] and
http://docs.oracle.com/javase/8/docs/api/java/awt/Component.html[java.awt.Component]
* https://github.com/apache/wicket[Apache Wicket] component tree,
see https://github.com/apache/wicket/blob/91e154702ab1ff3481ef6cbb04c6044814b7e130/wicket-core/src/main/java/org/apache/wicket/Component.java[Component] and https://github.com/apache/wicket/blob/b60ec64d0b50a611a9549809c9ab216f0ffa3ae3/wicket-core/src/main/java/org/apache/wicket/MarkupContainer.java[MarkupContainer]

## Credits

* http://www.amazon.com/Design-Patterns-Elements-Reusable-Object-Oriented/dp/0201633612[Design Patterns: Elements of Reusable Object-Oriented Software]
